# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    systemd:
      repo: 'puppet/systemd'
      ref: '3.10.0'
    concat:
      repo: 'puppetlabs/concat'
      ref: '7.2.0'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '8.2.0'
